CREATE TABLE PERSON (PERSONID INT PRIMARY KEY, FIRSTNAME VARCHAR(15) NOT NULL, MIDDLENAME VARCHAR(15), LASTNAME VARCHAR(15) NOT NULL, USERID VARCHAR(15) NOT NULL, PASSWORD VARCHAR(10) NOT NULL);

INSERT INTO PERSON VALUES(1, 'Fred', 'F', 'Flintstone', 'flintstonef', 'pebbles');
